name: Linux CI

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      OS: 'linux'
    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v2
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          python-version: 3.8
          use-only-tar-bz2: true
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install --file requirements/run.txt -c conda-forge -y -q
          conda install --file requirements/test.txt -c conda-forge -y -q
          python -m pip install git+https://github.com/goanpeca/spyder.git@fix/internal-plugs-for-ext-tests
      - name: Show test environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
#      - name: Run manifest checks
#        shell: bash -l {0}
#        run: check-manifest
#      - name: Run tests
#        shell: bash -l {0}
#        run: |
#          xvfb-run --auto-servernum pytest tests/ATE/data --cov=ATE
#          xvfb-run --auto-servernum pytest tests/ATE/TCC --cov=ATE
#          xvfb-run --auto-servernum pytest tests/ATE/spyder --cov=ATE
#          xvfb-run --auto-servernum pytest tests/ATE/TES/apps --cov=ATE
