name: Linux CI

on:
  release:
    branches:
      - "v*"    
jobs:
  build:
    name: cd
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      OS: 'linux'
    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v2
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          python-version: 3.8
          use-only-tar-bz2: true
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install --file requirements/run.txt -c conda-forge -y -q
          conda install --file requirements/test.txt -c conda-forge -y -q
          python -m pip install git+https://github.com/goanpeca/spyder.git@fix/internal-plugs-for-ext-tests
      - name: Show test environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
#      - name: build package
#        run: |
#          conda-build .........
#      - name: Upload the Build Artifacts
#        uses: actions/upload-artifact@v2.1.4
#        with:
#          # Artifact name
#          pcb-tester.asdf 
